### ISSUE TITLE
silent=False may cause the rainforest to die

### ISSUE THREAD

**Issue by willkg** [mozilla/puente#33]
I had the best of intentions when setting silent=False automatically. However, I misread the Jinja2 code. I thought it'd just print out the errors and move on. I didn't realize it'd print out the error and then set itself on fire and die an agonizing death. That's totally not what we want.

Given that, we should nix it automatically getting added.

**Comment by robhudson** [comment]
I would like it to be a command line option, however. It uncovered a lot of problems we should fix.

**Comment by willkg** [comment]
pybabel doesn't have this as a command line option. It's not too hard to add--you just set `JINJA_CONFIG` yourself rather than have Puente figure it out for you. Having said that, that's not wildly convenient.

We could make it another setting, but that feels a bit weird.

I don't have other ideas.

**Comment by willkg** [comment]
Oh, I know! How about we automatically add it on Mondays and the rest of the week, it doesn't get automatically added. Is that a good idea?

**Comment by willkg** [comment]
Rob fixed MDN to work with everything while having silent=False. In doing that, he discovered bugs in MDN!

After talking about this some more, we decided to leave it with silent=False for now since that will uncover issues.

**Comment by willkg** [comment]
This uncovered a bunch of template issues and that turned out to be really good. I'm going to leave this in and close this out for now.
