### ISSUE TITLE
puente needs a logo

### ISSUE THREAD

**Issue by willkg** [mozilla/puente#37]
We need a logo. Something that really evokes the underlying reason for existence for this project.

As soon as we come up with an idea, I'll draw it freehand in gimp.

**Comment by mythmon** [comment]
A bridge with a pile of explosive at one end, primed for detonation.

**Comment by jezdez** [comment]
@mythmon +1

**Comment by willkg** [comment]
This doesn't have the explosives. I was getting ready to draw that and then it occurred to me that it's pretty violent and I wasn't sure what it says to people who aren't in on the joke so I decided not to do it for now.

**Comment by mythmon** [comment]
Wow. That's actually a lot better than I was expecting. Nice job! Good call on the explosives.
