### ISSUE TITLE
endgame: look into merging extract and merge commands into a makemessages command a la django

### ISSUE THREAD

**Issue by willkg** [mozilla/puente#4]
Django has a makemessages command that does both extract and merge. Why did Tower separate the two steps? Can we merge the two commands into one thus getting us closer to vanilla Django?

**Comment by mythmon** [comment]
One possible reason I can think of for this separation is that in some apps, you have other extraction steps. For example, Sumo has extract steps (in theory) for BuddyUp and Yaocho. It would be possible to always use a combined step last, but it might be nice to have the freedom to do it in other orders.

That being said, I think even in Sumo I always run extract and merge together. Maybe a good compromise would be to have a makemessage command that simply runs the extract and merge commands together, and advertise that as the preferred method.

**Comment by willkg** [comment]
@robhudson Found this:

https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#message-files

I think that suggests this idea of converging towards makemessages and compilemessages isn't a hot idea.

Instead, we should converge on Babel's way of doing things possibly with the endgame of dropping all this for `pybabel` stuff.

Closing this out.
