### ISSUE TITLE
ditch STANDALONE_DOMAINS

### ISSUE THREAD

**Issue by willkg** [mozilla/puente#44]
We inherited `STANDALONE_DOMAINS` from Tower. The code is still in the extract and merge commands, but the setting isn't documented in the docs and the default is to merge all the extracted strings into one `.pot` file regardless of what `DOMAIN_METHODS` is which I don't think is a good default. A better default would be to have one `.pot` file for each domain.

I checked Input and MDN and they're not using this feature. SUMO uses it, but doesn't need to--they could trivially tweak their configuration so they didn't need it anymore. I don't know of anyone else using it and can't think of a compelling reason to keep it around.

Given that, I think we should ditch the `STANDALONE_DOMAINS` code from the extract and merge commands. Instead, each domain listed in `DOMAIN_METHODS` should get its own `.pot` file.

**Comment by robhudson** [comment]
:+1:

**Comment by willkg** [comment]
Fixed in #46. Yay!
