### ISSUE TITLE
./manage.py merge tries to merge LC_MESSAGES

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/puente#58]
In a run of `./manage.py merge` in the kuma project:

```
Merging javascript.po for ka
............ done.
Merging javascript.po for ko
.............. done.
 Can not find (/home/vagrant/src/locale/LC_MESSAGES/LC_MESSAGES/javascript.po).  Creating...
msginit: cannot create output file "/home/vagrant/src/locale/LC_MESSAGES/LC_MESSAGES/javascript.po": No such file or directory
Merging javascript.po for LC_MESSAGES
msgmerge: error while opening "/home/vagrant/src/locale/LC_MESSAGES/LC_MESSAGES/javascript.po" for reading: No such file or directory
Merging javascript.po for ln
............. done.
Merging javascript.po for mg
............ done.
```

Merge should detect a locale name of `LC_MESSAGES` and skip merging.

**Comment by willkg** [comment]
Maybe generalize it to "puente shouldn't merge on non-locales", but then it needs to know how to figure out what is and what isn't a locale. I don't think we'd be able to do that without creating other problems because locales aren't standard and there are pseudo-locales.

Does it just print a few errors like this and move onward? Or does the problem have bigger consequences?

**Comment by jwhitlock** [comment]
An `os.path.isdir` check would skip this and other random files.

It prints an error an moves on. The only effect is to freak out someone who has never generated locale strings before.

**Comment by willkg** [comment]
I looked at the kuma locale/ directory and I misunderstood the problem before.

I have no idea why it's looking at `/home/vagrant/src/locale/LC_MESSAGES/` at all. That's not a directory in `locale/`. puente should only be looking at directories in `locale/`.

Maybe something is wrong with how puente is listing that directory? Maybe puente isn't handling the way you're calling merge or a setting value well causing it to look int the wrong place?

**Comment by jwhitlock** [comment]
It looks like `locale/LC_MESSAGES` is an invalid folder. It is empty, and not in source control. I can only assume it was created by running our translation scripts in an invalid way. Re-running them [as documented](https://kuma.readthedocs.org/en/latest/localization.html) does not create the folder.

Sorry for the confusion, it looks like this was an invalid bug.

**Comment by willkg** [comment]
No worries! Might be nice if puente was smarter about things, but I'm not sure how to do that well.
