### ISSUE TITLE
Incompatible with Django 1.10 due to option_list being deprecated

### ISSUE THREAD

**Issue by thor** [mozilla/puente#59]
[In Django 1.8 `option_list` was depracted in favour of implementing `add_arguments`](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#accepting-optional-arguments), and as such with Django's deprecation policy, the former way was removed in 1.10.

The recommended fix is to implement `add_argument(self, parser)` in the management modules.

**Comment by willkg** [comment]
@thor Is there anything else you want to do? If not, do you want me to do a release?

**Comment by thor** [comment]
@willkg Nothing that I can come to think of right now! Any small change to the documentation or so doesn't need to be in this release, so I'm all for a release. Thanks for your help! ⭐️

**Comment by willkg** [comment]
Released 0.5 just now. Let me know if there are any problems. Thank you for fixing Django >= 1.9 support!
