### ISSUE TITLE
Merge command leaves domain POT file open

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/puente#71]
Tests raise this warning:

```
tests/test_merge.py::TestMergecommand::test_basic
  /home/travis/build/mozilla/puente/puente/commands.py:201: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-travis/pytest-0/test_basic0/locale/templates/LC_MESSAGES/django.pot' mode='r' encoding='UTF-8'>
    domain_pot_file = open(domain_pot)
```

My reading of the code is that when the locale is ``en_US``, the file is left open:

https://github.com/mozilla/puente/blob/4e22c22756cb07b44462ffc7c6a9ec20fc8e572e/puente/commands.py#L201-L223

It may be possible to eliminate the warning by closing ``domain_pot_file`` before leaving the ``if`` clause. A larger change would be to modify the code to use a context manager.

**Comment by willkg** [comment]
I think I'd go with the context manager. I can review if you need another set of eyes.
