### ISSUE TITLE
add db strings extraction command?

### ISSUE THREAD

**Issue by willkg** [mozilla/puente#9]
SUMO has some infrastructure for extracting strings from the database and putting them in a Python file which then gets passed over for strings extraction.

Input is going to need that, too.

Can we add that to Puente?

**Comment by mythmon** [comment]
The relevant part of the Sumo infrastructure is [`kitsune/sumo/management/commands/extract_db.py`](https://github.com/mozilla/kitsune/blob/0f93a47fa54fd884c39ddd0515a5729238db116d/kitsune/sumo/management/commands/extract_db.py).

**Comment by willkg** [comment]
I think I'm going to nix this idea. Less features makes it easier to ditch this library down the road.
